# Generated by Django 4.1 on 2023-12-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dateCompleted",
            field=models.DateTimeField(null=True),
        ),
    ]
